### ISSUE TITLE
Unable to send metrics error

### ISSUE THREAD

**Issue by acarbonaro** [nickbabcock/OhmGraphite#145]
When running `OhmGraphite` using the following command, the process starts and seems to add sensors, but loops through an exception.

`C:\Monitoring\OhmGraphite-0.14.0\OhmGraphite.exe run`

I can run `LibreHardwareMonitor` as a GUI and see all the proper data.

Here's the exception:
```
2020-06-01 12:53:44.0342|ERROR|OhmGraphite.MetricTimer|Unable to send metrics!System.ArgumentNullException: Value cannot be null.
Parameter name: stringToEscape
   at System.Uri.EscapeDataString(String stringToEscape)
   at InfluxDB.LineProtocol.Client.LineProtocolClient.<OnSendAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OhmGraphite.InfluxWriter.<ReportMetrics>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OhmGraphite.MetricTimer.<ReportMetrics>d__6.MoveNext()
```

And here's the full output from `OhmGraphite.exe`:
```
PS C:\Monitoring\OhmGraphite-0.14.0> C:\Monitoring\OhmGraphite-0.14.0\OhmGraphite.exe run
2020-06-01 13:49:47.6166|INFO|OhmGraphite.Program|Influxdb address: http://192.168.1.29:8086/ db: gaming
2020-06-01 13:49:47.6825|INFO|Topshelf.HostFactory|Configuration Result:
[Success] Name OhmGraphite
[Success] DisplayName Ohm Graphite
[Success] Description Extract hardware sensor data and exports it to a given host and port in a graphite compatible format
[Success] ServiceName OhmGraphite
2020-06-01 13:49:47.6893|INFO|Topshelf.HostConfigurators.HostConfiguratorImpl|Topshelf v4.2.1.215, .NET Framework v4.0.30319.42000
2020-06-01 13:49:47.7892|INFO|OhmGraphite.SensorCollector|Sensor added: /lpc/nct6791d/control/0 "Fan Control #1"
2020-06-01 13:49:47.7892|INFO|OhmGraphite.SensorCollector|Sensor added: /lpc/nct6791d/control/1 "Fan Control #2"
2020-06-01 13:49:47.7892|INFO|OhmGraphite.SensorCollector|Sensor added: /lpc/nct6791d/control/2 "Fan Control #3"
2020-06-01 13:49:47.7892|INFO|OhmGraphite.SensorCollector|Sensor added: /lpc/nct6791d/control/3 "Fan Control #4"
2020-06-01 13:49:47.7892|INFO|OhmGraphite.SensorCollector|Sensor added: /lpc/nct6791d/control/4 "Fan Control #5"
2020-06-01 13:49:47.7892|INFO|OhmGraphite.SensorCollector|Sensor added: /lpc/nct6791d/control/5 "Fan Control #6"
2020-06-01 13:49:47.8466|INFO|OhmGraphite.SensorCollector|Sensor added: /intelcpu/0/load/1 "CPU Core #1"
2020-06-01 13:49:47.8466|INFO|OhmGraphite.SensorCollector|Sensor added: /intelcpu/0/load/2 "CPU Core #2"
2020-06-01 13:49:47.8466|INFO|OhmGraphite.SensorCollector|Sensor added: /intelcpu/0/load/3 "CPU Core #3"
2020-06-01 13:49:47.8466|INFO|OhmGraphite.SensorCollector|Sensor added: /intelcpu/0/load/4 "CPU Core #4"
2020-06-01 13:49:47.8466|INFO|OhmGraphite.SensorCollector|Sensor added: /intelcpu/0/load/0 "CPU Total"
2020-06-01 13:49:47.8466|INFO|OhmGraphite.SensorCollector|Sensor added: /intelcpu/0/temperature/0 "CPU Core #1"
2020-06-01 13:49:47.8466|INFO|OhmGraphite.SensorCollector|Sensor added: /intelcpu/0/temperature/1 "CPU Core #2"
2020-06-01 13:49:47.8466|INFO|OhmGraphite.SensorCollector|Sensor added: /intelcpu/0/temperature/2 "CPU Core #3"
2020-06-01 13:49:47.8466|INFO|OhmGraphite.SensorCollector|Sensor added: /intelcpu/0/temperature/3 "CPU Core #4"
2020-06-01 13:49:47.8466|INFO|OhmGraphite.SensorCollector|Sensor added: /intelcpu/0/temperature/4 "CPU Package"
2020-06-01 13:49:47.8466|INFO|OhmGraphite.SensorCollector|Sensor added: /intelcpu/0/temperature/5 "CPU Core #1 Distance to TjMax"
2020-06-01 13:49:47.8466|INFO|OhmGraphite.SensorCollector|Sensor added: /intelcpu/0/temperature/6 "CPU Core #2 Distance to TjMax"
2020-06-01 13:49:47.8466|INFO|OhmGraphite.SensorCollector|Sensor added: /intelcpu/0/temperature/7 "CPU Core #3 Distance to TjMax"
2020-06-01 13:49:47.8466|INFO|OhmGraphite.SensorCollector|Sensor added: /intelcpu/0/temperature/8 "CPU Core #4 Distance to TjMax"
2020-06-01 13:49:47.8466|INFO|OhmGraphite.SensorCollector|Sensor added: /intelcpu/0/temperature/9 "Core Max"
2020-06-01 13:49:47.8466|INFO|OhmGraphite.SensorCollector|Sensor added: /intelcpu/0/temperature/10 "Core Average"
2020-06-01 13:49:47.8466|INFO|OhmGraphite.SensorCollector|Sensor added: /intelcpu/0/clock/1 "CPU Core #1"
2020-06-01 13:49:47.8466|INFO|OhmGraphite.SensorCollector|Sensor added: /intelcpu/0/clock/2 "CPU Core #2"
2020-06-01 13:49:47.8466|INFO|OhmGraphite.SensorCollector|Sensor added: /intelcpu/0/clock/3 "CPU Core #3"
2020-06-01 13:49:47.8466|INFO|OhmGraphite.SensorCollector|Sensor added: /intelcpu/0/clock/4 "CPU Core #4"
2020-06-01 13:49:47.8466|INFO|OhmGraphite.SensorCollector|Sensor added: /intelcpu/0/power/0 "CPU Package"
2020-06-01 13:49:47.8466|INFO|OhmGraphite.SensorCollector|Sensor added: /intelcpu/0/power/1 "CPU Cores"
2020-06-01 13:49:47.8466|INFO|OhmGraphite.SensorCollector|Sensor added: /intelcpu/0/power/2 "CPU Graphics"
2020-06-01 13:49:47.8599|INFO|OhmGraphite.SensorCollector|Sensor added: /intelcpu/0/power/3 "CPU Memory"
2020-06-01 13:49:47.8599|INFO|OhmGraphite.SensorCollector|Sensor added: /intelcpu/0/clock/0 "Bus Speed"
2020-06-01 13:49:47.8599|INFO|OhmGraphite.SensorCollector|Sensor added: /ram/data/0 "Memory Used"
2020-06-01 13:49:47.8599|INFO|OhmGraphite.SensorCollector|Sensor added: /ram/data/1 "Memory Available"
2020-06-01 13:49:47.8599|INFO|OhmGraphite.SensorCollector|Sensor added: /ram/load/0 "Memory"
2020-06-01 13:49:47.8599|INFO|OhmGraphite.SensorCollector|Sensor added: /ram/data/2 "Virtual Memory Used"
2020-06-01 13:49:47.8599|INFO|OhmGraphite.SensorCollector|Sensor added: /ram/data/3 "Virtual Memory Available"
2020-06-01 13:49:47.8599|INFO|OhmGraphite.SensorCollector|Sensor added: /ram/load/1 "Virtual Memory"
2020-06-01 13:49:47.9576|INFO|OhmGraphite.SensorCollector|Sensor added: /gpu/0/temperature/0 "GPU Core"
2020-06-01 13:49:47.9576|INFO|OhmGraphite.SensorCollector|Sensor added: /gpu/0/clock/0 "GPU Core"
2020-06-01 13:49:47.9576|INFO|OhmGraphite.SensorCollector|Sensor added: /gpu/0/clock/1 "GPU Memory"
2020-06-01 13:49:47.9576|INFO|OhmGraphite.SensorCollector|Sensor added: /gpu/0/clock/2 "GPU Shader"
2020-06-01 13:49:47.9576|INFO|OhmGraphite.SensorCollector|Sensor added: /gpu/0/fan/0 "GPU"
2020-06-01 13:49:47.9576|INFO|OhmGraphite.SensorCollector|Sensor added: /gpu/0/load/0 "GPU Core"
2020-06-01 13:49:47.9576|INFO|OhmGraphite.SensorCollector|Sensor added: /gpu/0/load/1 "GPU Memory Controller"
2020-06-01 13:49:47.9576|INFO|OhmGraphite.SensorCollector|Sensor added: /gpu/0/load/2 "GPU Video Engine"
2020-06-01 13:49:47.9576|INFO|OhmGraphite.SensorCollector|Sensor added: /gpu/0/load/4 "GPU Bus"
2020-06-01 13:49:47.9576|INFO|OhmGraphite.SensorCollector|Sensor added: /gpu/0/control/0 "GPU Fan"
2020-06-01 13:49:47.9576|INFO|OhmGraphite.SensorCollector|Sensor added: /gpu/0/smalldata/3 "GPU Memory Total"
2020-06-01 13:49:47.9576|INFO|OhmGraphite.SensorCollector|Sensor added: /gpu/0/smalldata/2 "GPU Memory Used"
2020-06-01 13:49:47.9576|INFO|OhmGraphite.SensorCollector|Sensor added: /gpu/0/smalldata/1 "GPU Memory Free"
2020-06-01 13:49:47.9576|INFO|OhmGraphite.SensorCollector|Sensor added: /gpu/0/load/3 "GPU Memory"
2020-06-01 13:49:47.9576|INFO|OhmGraphite.SensorCollector|Sensor added: /gpu/0/power/0 "GPU Package"
2020-06-01 13:49:47.9576|INFO|OhmGraphite.SensorCollector|Sensor added: /gpu/0/throughput/0 "GPU PCIe Rx"
2020-06-01 13:49:47.9576|INFO|OhmGraphite.SensorCollector|Sensor added: /gpu/0/throughput/1 "GPU PCIe Tx"
2020-06-01 13:49:48.5212|INFO|OhmGraphite.SensorCollector|Sensor added: /nvme/0/temperature/0 "Temperature"
2020-06-01 13:49:48.5212|INFO|OhmGraphite.SensorCollector|Sensor added: /nvme/0/level/1 "Available Spare"
2020-06-01 13:49:48.5212|INFO|OhmGraphite.SensorCollector|Sensor added: /nvme/0/level/2 "Available Spare Threshold"
2020-06-01 13:49:48.5212|INFO|OhmGraphite.SensorCollector|Sensor added: /nvme/0/level/3 "Percentage Used"
2020-06-01 13:49:48.5212|INFO|OhmGraphite.SensorCollector|Sensor added: /nvme/0/data/4 "Data Read"
2020-06-01 13:49:48.5212|INFO|OhmGraphite.SensorCollector|Sensor added: /nvme/0/data/5 "Data Written"
2020-06-01 13:49:48.5212|INFO|OhmGraphite.SensorCollector|Sensor added: /nvme/0/temperature/6 "Temperature 1"
2020-06-01 13:49:48.5212|INFO|OhmGraphite.SensorCollector|Sensor added: /nvme/0/temperature/7 "Temperature 2"
2020-06-01 13:49:48.5212|INFO|OhmGraphite.SensorCollector|Sensor added: /nvme/0/load/0 "Used Space"
2020-06-01 13:49:48.5212|INFO|OhmGraphite.SensorCollector|Sensor added: /nvme/0/load/32 "Write Activity"
2020-06-01 13:49:48.5212|INFO|OhmGraphite.SensorCollector|Sensor added: /nvme/0/load/33 "Total Activity"
2020-06-01 13:49:48.5212|INFO|OhmGraphite.SensorCollector|Sensor added: /nvme/0/throughput/34 "Read Rate"
2020-06-01 13:49:48.5212|INFO|OhmGraphite.SensorCollector|Sensor added: /nvme/0/throughput/35 "Write Rate"
2020-06-01 13:49:48.5212|INFO|OhmGraphite.SensorCollector|Sensor added: /nvme/0/factor/media_errors "Media Errors"
2020-06-01 13:49:48.5212|INFO|OhmGraphite.SensorCollector|Sensor added: /nvme/0/factor/power_cycles "Power Cycles"
2020-06-01 13:49:48.5212|INFO|OhmGraphite.SensorCollector|Sensor added: /nvme/0/factor/error_info_log_entries "Error Info Log Entries"
2020-06-01 13:49:48.5212|INFO|OhmGraphite.SensorCollector|Sensor added: /nvme/0/factor/unsafe_shutdowns "Unsafe Shutdowns"
2020-06-01 13:49:48.5212|INFO|OhmGraphite.SensorCollector|Sensor added: /ssd/1/temperature/0 "Temperature"
2020-06-01 13:49:48.5324|INFO|OhmGraphite.SensorCollector|Sensor added: /ssd/1/data/0 "Total Bytes Written"
2020-06-01 13:49:48.5324|INFO|OhmGraphite.SensorCollector|Sensor added: /ssd/1/load/0 "Used Space"
2020-06-01 13:49:48.5324|INFO|OhmGraphite.SensorCollector|Sensor added: /ssd/1/load/32 "Write Activity"
2020-06-01 13:49:48.5324|INFO|OhmGraphite.SensorCollector|Sensor added: /ssd/1/load/33 "Total Activity"
2020-06-01 13:49:48.5324|INFO|OhmGraphite.SensorCollector|Sensor added: /ssd/1/throughput/34 "Read Rate"
2020-06-01 13:49:48.5324|INFO|OhmGraphite.SensorCollector|Sensor added: /ssd/1/throughput/35 "Write Rate"
2020-06-01 13:49:48.7382|INFO|OhmGraphite.SensorCollector|Sensor added: /nic/{5F02ECD9-DB56-4927-AC8B-BFBB27B5FA93}/data/2 "Data Uploaded"
2020-06-01 13:49:48.7382|INFO|OhmGraphite.SensorCollector|Sensor added: /nic/{5F02ECD9-DB56-4927-AC8B-BFBB27B5FA93}/data/3 "Data Downloaded"
2020-06-01 13:49:48.7382|INFO|OhmGraphite.SensorCollector|Sensor added: /nic/{5F02ECD9-DB56-4927-AC8B-BFBB27B5FA93}/throughput/7 "Upload Speed"
2020-06-01 13:49:48.7382|INFO|OhmGraphite.SensorCollector|Sensor added: /nic/{5F02ECD9-DB56-4927-AC8B-BFBB27B5FA93}/throughput/8 "Download Speed"
2020-06-01 13:49:48.7382|INFO|OhmGraphite.SensorCollector|Sensor added: /nic/{5F02ECD9-DB56-4927-AC8B-BFBB27B5FA93}/load/1 "Network Utilization"
2020-06-01 13:49:48.7382|INFO|OhmGraphite.SensorCollector|Sensor added: /nic/{4F3BADD3-42A0-4C70-BFB6-FC170A0916E8}/data/2 "Data Uploaded"
2020-06-01 13:49:48.7382|INFO|OhmGraphite.SensorCollector|Sensor added: /nic/{4F3BADD3-42A0-4C70-BFB6-FC170A0916E8}/data/3 "Data Downloaded"
2020-06-01 13:49:48.7382|INFO|OhmGraphite.SensorCollector|Sensor added: /nic/{4F3BADD3-42A0-4C70-BFB6-FC170A0916E8}/throughput/7 "Upload Speed"
2020-06-01 13:49:48.7382|INFO|OhmGraphite.SensorCollector|Sensor added: /nic/{4F3BADD3-42A0-4C70-BFB6-FC170A0916E8}/throughput/8 "Download Speed"
2020-06-01 13:49:48.7382|INFO|OhmGraphite.SensorCollector|Sensor added: /nic/{4F3BADD3-42A0-4C70-BFB6-FC170A0916E8}/load/1 "Network Utilization"
2020-06-01 13:49:48.7382|INFO|OhmGraphite.SensorCollector|Sensor added: /nic/{D3D36BA9-9896-41D4-B153-0E2CFE41C534}/data/2 "Data Uploaded"
2020-06-01 13:49:48.7382|INFO|OhmGraphite.SensorCollector|Sensor added: /nic/{D3D36BA9-9896-41D4-B153-0E2CFE41C534}/data/3 "Data Downloaded"
2020-06-01 13:49:48.7382|INFO|OhmGraphite.SensorCollector|Sensor added: /nic/{D3D36BA9-9896-41D4-B153-0E2CFE41C534}/throughput/7 "Upload Speed"
2020-06-01 13:49:48.7382|INFO|OhmGraphite.SensorCollector|Sensor added: /nic/{D3D36BA9-9896-41D4-B153-0E2CFE41C534}/throughput/8 "Download Speed"
2020-06-01 13:49:48.7382|INFO|OhmGraphite.SensorCollector|Sensor added: /nic/{D3D36BA9-9896-41D4-B153-0E2CFE41C534}/load/1 "Network Utilization"
2020-06-01 13:49:48.7382|INFO|OhmGraphite.SensorCollector|Sensor added: /nic/{EF18B914-72BF-4D67-AD4B-16EBA4524F64}/data/2 "Data Uploaded"
2020-06-01 13:49:48.7382|INFO|OhmGraphite.SensorCollector|Sensor added: /nic/{EF18B914-72BF-4D67-AD4B-16EBA4524F64}/data/3 "Data Downloaded"
2020-06-01 13:49:48.7382|INFO|OhmGraphite.SensorCollector|Sensor added: /nic/{EF18B914-72BF-4D67-AD4B-16EBA4524F64}/throughput/7 "Upload Speed"
2020-06-01 13:49:48.7382|INFO|OhmGraphite.SensorCollector|Sensor added: /nic/{EF18B914-72BF-4D67-AD4B-16EBA4524F64}/throughput/8 "Download Speed"
2020-06-01 13:49:48.7382|INFO|OhmGraphite.SensorCollector|Sensor added: /nic/{EF18B914-72BF-4D67-AD4B-16EBA4524F64}/load/1 "Network Utilization"
2020-06-01 13:49:48.7382|INFO|OhmGraphite.SensorCollector|Sensor added: /nic/{1C2FBA5E-9C8D-4876-877E-70FD91477545}/data/2 "Data Uploaded"
2020-06-01 13:49:48.7382|INFO|OhmGraphite.SensorCollector|Sensor added: /nic/{1C2FBA5E-9C8D-4876-877E-70FD91477545}/data/3 "Data Downloaded"
2020-06-01 13:49:48.7506|INFO|OhmGraphite.SensorCollector|Sensor added: /nic/{1C2FBA5E-9C8D-4876-877E-70FD91477545}/throughput/7 "Upload Speed"
2020-06-01 13:49:48.7506|INFO|OhmGraphite.SensorCollector|Sensor added: /nic/{1C2FBA5E-9C8D-4876-877E-70FD91477545}/throughput/8 "Download Speed"
2020-06-01 13:49:48.7506|INFO|OhmGraphite.SensorCollector|Sensor added: /nic/{1C2FBA5E-9C8D-4876-877E-70FD91477545}/load/1 "Network Utilization"
2020-06-01 13:49:48.7506|INFO|OhmGraphite.SensorCollector|Sensor added: /nic/{44879B29-07E4-4E02-A8FA-5F947AB3E0BE}/data/2 "Data Uploaded"
2020-06-01 13:49:48.7506|INFO|OhmGraphite.SensorCollector|Sensor added: /nic/{44879B29-07E4-4E02-A8FA-5F947AB3E0BE}/data/3 "Data Downloaded"
2020-06-01 13:49:48.7506|INFO|OhmGraphite.SensorCollector|Sensor added: /nic/{44879B29-07E4-4E02-A8FA-5F947AB3E0BE}/throughput/7 "Upload Speed"
2020-06-01 13:49:48.7506|INFO|OhmGraphite.SensorCollector|Sensor added: /nic/{44879B29-07E4-4E02-A8FA-5F947AB3E0BE}/throughput/8 "Download Speed"
2020-06-01 13:49:48.7506|INFO|OhmGraphite.SensorCollector|Sensor added: /nic/{44879B29-07E4-4E02-A8FA-5F947AB3E0BE}/load/1 "Network Utilization"
2020-06-01 13:49:48.7506|INFO|OhmGraphite.SensorCollector|Sensor added: /nic/{E2E10ED1-A00C-4597-B841-EFBF1D410A4E}/data/2 "Data Uploaded"
2020-06-01 13:49:48.7506|INFO|OhmGraphite.SensorCollector|Sensor added: /nic/{E2E10ED1-A00C-4597-B841-EFBF1D410A4E}/data/3 "Data Downloaded"
2020-06-01 13:49:48.7506|INFO|OhmGraphite.SensorCollector|Sensor added: /nic/{E2E10ED1-A00C-4597-B841-EFBF1D410A4E}/throughput/7 "Upload Speed"
2020-06-01 13:49:48.7506|INFO|OhmGraphite.SensorCollector|Sensor added: /nic/{E2E10ED1-A00C-4597-B841-EFBF1D410A4E}/throughput/8 "Download Speed"
2020-06-01 13:49:48.7506|INFO|OhmGraphite.SensorCollector|Sensor added: /nic/{E2E10ED1-A00C-4597-B841-EFBF1D410A4E}/load/1 "Network Utilization"
2020-06-01 13:49:48.7506|INFO|Topshelf.Hosts.ConsoleRunHost|The OhmGraphite service is now running, press Control+C to exit.
2020-06-01 13:49:53.7641|INFO|OhmGraphite.SensorCollector|Sensor added: /lpc/nct6791d/voltage/0 "Vcore"
2020-06-01 13:49:53.7641|INFO|OhmGraphite.SensorCollector|Sensor added: /lpc/nct6791d/voltage/1 "Voltage #2"
2020-06-01 13:49:53.7661|INFO|OhmGraphite.SensorCollector|Sensor added: /lpc/nct6791d/voltage/2 "AVCC"
2020-06-01 13:49:53.7661|INFO|OhmGraphite.SensorCollector|Sensor added: /lpc/nct6791d/voltage/3 "+3.3V"
2020-06-01 13:49:53.7661|INFO|OhmGraphite.SensorCollector|Sensor added: /lpc/nct6791d/voltage/4 "Voltage #5"
2020-06-01 13:49:53.7661|INFO|OhmGraphite.SensorCollector|Sensor added: /lpc/nct6791d/voltage/5 "Voltage #6"
2020-06-01 13:49:53.7661|INFO|OhmGraphite.SensorCollector|Sensor added: /lpc/nct6791d/voltage/6 "Voltage #7"
2020-06-01 13:49:53.7661|INFO|OhmGraphite.SensorCollector|Sensor added: /lpc/nct6791d/voltage/7 "3VSB"
2020-06-01 13:49:53.7661|INFO|OhmGraphite.SensorCollector|Sensor added: /lpc/nct6791d/voltage/9 "VTT"
2020-06-01 13:49:53.7661|INFO|OhmGraphite.SensorCollector|Sensor added: /lpc/nct6791d/voltage/10 "Voltage #11"
2020-06-01 13:49:53.7661|INFO|OhmGraphite.SensorCollector|Sensor added: /lpc/nct6791d/voltage/11 "Voltage #12"
2020-06-01 13:49:53.7661|INFO|OhmGraphite.SensorCollector|Sensor added: /lpc/nct6791d/voltage/12 "Voltage #13"
2020-06-01 13:49:53.7661|INFO|OhmGraphite.SensorCollector|Sensor added: /lpc/nct6791d/voltage/13 "Voltage #14"
2020-06-01 13:49:53.7661|INFO|OhmGraphite.SensorCollector|Sensor added: /lpc/nct6791d/voltage/14 "Voltage #15"
2020-06-01 13:49:53.7661|INFO|OhmGraphite.SensorCollector|Sensor added: /lpc/nct6791d/temperature/0 "CPU Core"
2020-06-01 13:49:53.7661|INFO|OhmGraphite.SensorCollector|Sensor added: /lpc/nct6791d/temperature/1 "Temperature #1"
2020-06-01 13:49:53.7661|INFO|OhmGraphite.SensorCollector|Sensor added: /lpc/nct6791d/temperature/2 "Temperature #2"
2020-06-01 13:49:53.7661|INFO|OhmGraphite.SensorCollector|Sensor added: /lpc/nct6791d/temperature/3 "Temperature #3"
2020-06-01 13:49:53.7661|INFO|OhmGraphite.SensorCollector|Sensor added: /lpc/nct6791d/temperature/4 "Temperature #4"
2020-06-01 13:49:53.7661|INFO|OhmGraphite.SensorCollector|Sensor added: /lpc/nct6791d/temperature/5 "Temperature #5"
2020-06-01 13:49:53.7661|INFO|OhmGraphite.SensorCollector|Sensor added: /lpc/nct6791d/temperature/6 "Temperature #6"
2020-06-01 13:49:53.7661|INFO|OhmGraphite.SensorCollector|Sensor added: /lpc/nct6791d/fan/0 "Fan #1"
2020-06-01 13:49:53.7661|INFO|OhmGraphite.SensorCollector|Sensor added: /lpc/nct6791d/fan/1 "Fan #2"
2020-06-01 13:49:53.7661|INFO|OhmGraphite.SensorCollector|Sensor added: /lpc/nct6791d/fan/2 "Fan #3"
2020-06-01 13:49:53.7661|INFO|OhmGraphite.SensorCollector|Sensor added: /lpc/nct6791d/fan/3 "Fan #4"
2020-06-01 13:49:53.7661|INFO|OhmGraphite.SensorCollector|Sensor added: /lpc/nct6791d/fan/4 "Fan #5"
2020-06-01 13:49:53.7661|INFO|OhmGraphite.SensorCollector|Sensor added: /lpc/nct6791d/fan/5 "Fan #6"
2020-06-01 13:49:53.9265|ERROR|OhmGraphite.MetricTimer|Unable to send metrics!System.ArgumentNullException: Value cannot be null.
Parameter name: stringToEscape
   at System.Uri.EscapeDataString(String stringToEscape)
   at InfluxDB.LineProtocol.Client.LineProtocolClient.<OnSendAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OhmGraphite.InfluxWriter.<ReportMetrics>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OhmGraphite.MetricTimer.<ReportMetrics>d__6.MoveNext()
2020-06-01 13:49:58.8290|ERROR|OhmGraphite.MetricTimer|Unable to send metrics!System.ArgumentNullException: Value cannot be null.
Parameter name: stringToEscape
   at System.Uri.EscapeDataString(String stringToEscape)
   at InfluxDB.LineProtocol.Client.LineProtocolClient.<OnSendAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OhmGraphite.InfluxWriter.<ReportMetrics>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OhmGraphite.MetricTimer.<ReportMetrics>d__6.MoveNext()
2020-06-01 13:49:59.4190|INFO|Topshelf.Hosts.ConsoleRunHost|Control+C detected, attempting to stop service.
2020-06-01 13:49:59.4938|INFO|Topshelf.Hosts.ConsoleRunHost|The OhmGraphite service has stopped.
```

**Comment by nickbabcock** [comment]
Post your OhmGraphite.exe.config: this is mine for influxdb and I can confirm that it is working:

```xml
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <appSettings>
    <add key="type" value="influxdb" />
    <add key="interval" value="5" />
    <add key="influx_address" value="http://10.0.0.201:8086" />
    <add key="influx_db" value="mydb" />
   </appSettings>
</configuration>
```

My best guess is that the username is specified without a password.

**Comment by acarbonaro** [comment]
Ah, that was it.  The user is passwordless, but the password key is necessary if there's a user.  Thank you!
