### ISSUE TITLE
Can not start OhmGraphite service in Windows 10 Pro

### ISSUE THREAD

**Issue by imbarto** [nickbabcock/OhmGraphite#161]
I have been using OhmGraphite for a while, unfortunately it started to make some trouble. I cannot start the service anymore, when I run  .\OhmGraphite.exe run I get this error. Reinstalling did not help 
 
```2020-09-21 17:53:33.3454|INFO|OhmGraphite.SensorCollector|Sensor added: /nic/{4B41FD5F-6169-4389-AABC-8DCC82F41CC8}/data/2 "Data Uploaded"
2020-09-21 17:53:33.3454|INFO|OhmGraphite.SensorCollector|Sensor added: /nic/{4B41FD5F-6169-4389-AABC-8DCC82F41CC8}/data/3 "Data Downloaded"
2020-09-21 17:53:33.3454|INFO|OhmGraphite.SensorCollector|Sensor added: /nic/{4B41FD5F-6169-4389-AABC-8DCC82F41CC8}/throughput/7 "Upload Speed"
2020-09-21 17:53:33.3454|INFO|OhmGraphite.SensorCollector|Sensor added: /nic/{4B41FD5F-6169-4389-AABC-8DCC82F41CC8}/throughput/8 "Download Speed"
2020-09-21 17:53:33.3454|INFO|OhmGraphite.SensorCollector|Sensor added: /nic/{4B41FD5F-6169-4389-AABC-8DCC82F41CC8}/load/1 "Network Utilization"
2020-09-21 17:53:33.3454|INFO|OhmGraphite.SensorCollector|Sensor added: /nic/{FCBF1FC4-1BEF-49A0-9B0A-0F049B2F2F34}/data/2 "Data Uploaded"
2020-09-21 17:53:33.3454|INFO|OhmGraphite.SensorCollector|Sensor added: /nic/{FCBF1FC4-1BEF-49A0-9B0A-0F049B2F2F34}/data/3 "Data Downloaded"
2020-09-21 17:53:33.3454|INFO|OhmGraphite.SensorCollector|Sensor added: /nic/{FCBF1FC4-1BEF-49A0-9B0A-0F049B2F2F34}/throughput/7 "Upload Speed"
2020-09-21 17:53:33.3454|INFO|OhmGraphite.SensorCollector|Sensor added: /nic/{FCBF1FC4-1BEF-49A0-9B0A-0F049B2F2F34}/throughput/8 "Download Speed"
2020-09-21 17:53:33.3454|INFO|OhmGraphite.SensorCollector|Sensor added: /nic/{FCBF1FC4-1BEF-49A0-9B0A-0F049B2F2F34}/load/1 "Network Utilization"
2020-09-21 17:53:33.3454|INFO|OhmGraphite.SensorCollector|Sensor added: /nic/{9382E7DA-B465-40A8-A4BA-C394A2FDCEFD}/data/2 "Data Uploaded"
2020-09-21 17:53:33.3454|INFO|OhmGraphite.SensorCollector|Sensor added: /nic/{9382E7DA-B465-40A8-A4BA-C394A2FDCEFD}/data/3 "Data Downloaded"
2020-09-21 17:53:33.3454|INFO|OhmGraphite.SensorCollector|Sensor added: /nic/{9382E7DA-B465-40A8-A4BA-C394A2FDCEFD}/throughput/7 "Upload Speed"
2020-09-21 17:53:33.3454|INFO|OhmGraphite.SensorCollector|Sensor added: /nic/{9382E7DA-B465-40A8-A4BA-C394A2FDCEFD}/throughput/8 "Download Speed"
2020-09-21 17:53:33.3454|INFO|OhmGraphite.SensorCollector|Sensor added: /nic/{9382E7DA-B465-40A8-A4BA-C394A2FDCEFD}/load/1 "Network Utilization"
2020-09-21 17:53:33.3454|INFO|OhmGraphite.SensorCollector|Sensor added: /nic/{5D7C2CD5-9A75-1AC5-6245-118F1C411193}/data/2 "Data Uploaded"
2020-09-21 17:53:33.3454|INFO|OhmGraphite.SensorCollector|Sensor added: /nic/{5D7C2CD5-9A75-1AC5-6245-118F1C411193}/data/3 "Data Downloaded"
2020-09-21 17:53:33.3454|INFO|OhmGraphite.SensorCollector|Sensor added: /nic/{5D7C2CD5-9A75-1AC5-6245-118F1C411193}/throughput/7 "Upload Speed"
2020-09-21 17:53:33.3454|INFO|OhmGraphite.SensorCollector|Sensor added: /nic/{5D7C2CD5-9A75-1AC5-6245-118F1C411193}/throughput/8 "Download Speed"
2020-09-21 17:53:33.3454|INFO|OhmGraphite.SensorCollector|Sensor added: /nic/{5D7C2CD5-9A75-1AC5-6245-118F1C411193}/load/1 "Network Utilization"
2020-09-21 17:53:33.3454|INFO|OhmGraphite.SensorCollector|Sensor added: /nic/{271D0142-8048-4C2B-BAC1-19CDBB270D29}/data/3 "Data Downloaded"
2020-09-21 17:53:33.3454|INFO|OhmGraphite.SensorCollector|Sensor added: /nic/{271D0142-8048-4C2B-BAC1-19CDBB270D29}/throughput/7 "Upload Speed"
2020-09-21 17:53:33.3454|INFO|OhmGraphite.SensorCollector|Sensor added: /nic/{271D0142-8048-4C2B-BAC1-19CDBB270D29}/throughput/8 "Download Speed"
2020-09-21 17:53:33.3454|INFO|OhmGraphite.SensorCollector|Sensor added: /nic/{271D0142-8048-4C2B-BAC1-19CDBB270D29}/load/1 "Network Utilization"
2020-09-21 17:53:33.3454|INFO|OhmGraphite.SensorCollector|Sensor added: /nic/{14C5E932-86A3-4B5C-B160-FAD66CB57E37}/data/2 "Data Uploaded"
2020-09-21 17:53:33.3454|INFO|OhmGraphite.SensorCollector|Sensor added: /nic/{14C5E932-86A3-4B5C-B160-FAD66CB57E37}/data/3 "Data Downloaded"
2020-09-21 17:53:33.3454|INFO|OhmGraphite.SensorCollector|Sensor added: /nic/{14C5E932-86A3-4B5C-B160-FAD66CB57E37}/throughput/7 "Upload Speed"
2020-09-21 17:53:33.3454|INFO|OhmGraphite.SensorCollector|Sensor added: /nic/{14C5E932-86A3-4B5C-B160-FAD66CB57E37}/throughput/8 "Download Speed"
2020-09-21 17:53:33.3454|INFO|OhmGraphite.SensorCollector|Sensor added: /nic/{14C5E932-86A3-4B5C-B160-FAD66CB57E37}/load/1 "Network Utilization"
2020-09-21 17:53:33.3454|ERROR|OhmGraphite.PrometheusServer|Exception: starting prometheus server!System.Net.HttpListenerException (0x80004005): The format of the specified network name is invalid
   at System.Net.HttpListener.AddAllPrefixes()
   at System.Net.HttpListener.Start()
   at Prometheus.MetricServer.StartServer(CancellationToken cancel)
   at Prometheus.MetricHandler.Start()
   at OhmGraphite.LoggerUtils.LogAction(Logger logger, String msg, Action action)
2020-09-21 17:53:33.3634|ERROR|OhmGraphite.Program|OhmGraphite TopShelf encountered an error!System.Exception: Exception with starting prometheus server ---> System.Net.HttpListenerException: The format of the specified network name is invalid
   at System.Net.HttpListener.AddAllPrefixes()
   at System.Net.HttpListener.Start()
   at Prometheus.MetricServer.StartServer(CancellationToken cancel)
   at Prometheus.MetricHandler.Start()
   at OhmGraphite.LoggerUtils.LogAction(Logger logger, String msg, Action action)
   --- End of inner exception stack trace ---
   at OhmGraphite.LoggerUtils.LogAction(Logger logger, String msg, Action action)
   at Topshelf.ServiceConfiguratorExtensions.<>c__DisplayClass2_0`1.<WhenStarted>b__0(T service, HostControl control)
   at Topshelf.Builders.DelegateServiceBuilder`1.DelegateServiceHandle.Start(HostControl hostControl)
   at Topshelf.Hosts.ConsoleRunHost.Run()
2020-09-21 17:53:33.3634|ERROR|Topshelf.Hosts.ConsoleRunHost|An exception occurred!System.Exception: Exception with starting prometheus server ---> System.Net.HttpListenerException: The format of the specified network name is invalid
   at System.Net.HttpListener.AddAllPrefixes()
   at System.Net.HttpListener.Start()
   at Prometheus.MetricServer.StartServer(CancellationToken cancel)
   at Prometheus.MetricHandler.Start()
   at OhmGraphite.LoggerUtils.LogAction(Logger logger, String msg, Action action)
   --- End of inner exception stack trace ---
   at OhmGraphite.LoggerUtils.LogAction(Logger logger, String msg, Action action)
   at Topshelf.ServiceConfiguratorExtensions.<>c__DisplayClass2_0`1.<WhenStarted>b__0(T service, HostControl control)
   at Topshelf.Builders.DelegateServiceBuilder`1.DelegateServiceHandle.Start(HostControl hostControl)
   at Topshelf.Hosts.ConsoleRunHost.Run()
```

**Comment by imbarto** [comment]
dupplicate sorry
