### ISSUE TITLE
TimescaleDB / Postgres: Cannot write DateTime with Kind=Local to PostgreSQL type 'timestamp with time zone'

### ISSUE THREAD

**Issue by mikeblum** [nickbabcock/OhmGraphite#273]
OhmGraphite Version: `0.23.0`
OS: `Windows 10 Pro`
Postgres Version: `14`

```
2021-12-23 18:18:18.5208|ERROR|OhmGraphite.MetricTimer|Unable to send metrics!System.InvalidCastException: Cannot write DateTime with Kind=Local to PostgreSQL type 'timestamp with time zone', only UTC is supported. Note that it's not possible to mix DateTimes with different Kinds in an array/range. See the Npgsql.EnableLegacyTimestampBehavior AppContext switch to enable legacy behavior.
   at Npgsql.Internal.TypeHandlers.DateTimeHandlers.TimestampTzHandler.ValidateAndGetLength(DateTime value, NpgsqlParameter parameter)
   at Npgsql.Internal.TypeHandlers.DateTimeHandlers.TimestampTzHandler.ValidateObjectAndGetLength(Object value, NpgsqlLengthCache& lengthCache, NpgsqlParameter parameter)
   at Npgsql.NpgsqlParameter.ValidateAndGetLength()
   at Npgsql.NpgsqlParameterCollection.ValidateAndBind(ConnectorTypeMapper typeMapper)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery()
   at OhmGraphite.TimescaleWriter.ReportMetrics(DateTime reportTime, IEnumerable`1 sensors)
   at OhmGraphite.MetricTimer.ReportMetrics(Object sender, ElapsedEventArgs e)
```

So far i attempted to set the `postgresql.conf` to `UTC`:

```
#timezone = 'America/Chicago'
timezone = 'UTC'
...
#log_timezone = 'America/Chicago'
log_timezone = 'UTC'
```

and I also attempted to tweak the column type to ignore timezones:

```
CREATE TABLE IF NOT EXISTS ohm_stats (
   time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   host TEXT,
   hardware TEXT,
   hardware_type TEXT,
   identifier TEXT,
   sensor TEXT,
   sensor_type TEXT,
   sensor_index INT,
   value REAL
);
```

as well as:

```
CREATE TABLE IF NOT EXISTS ohm_stats (
   time TIMESTAMP NOT NULL,
   host TEXT,
   hardware TEXT,
   hardware_type TEXT,
   identifier TEXT,
   sensor TEXT,
   sensor_type TEXT,
   sensor_index INT,
   value REAL
);
```

 but still getting the above stacktrace.

Here is my ohmgraphite.exe.config:

```
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <appSettings>
    <add key="type" value="timescale" />
    <add key="timescale_connection" value="Host=localhost;Username=ohm;Password=??????;Database=postgres" />
    <add key="timescale_setup" value="false" />
  </appSettings>
</configuration>
```

as well as with the root `postgres` user and `timescale_setup` = `true` and got the same result.

restarted the postgres and OHMGraphite Windows services after each of these changes.

Found this section of the docs: https://www.npgsql.org/doc/types/datetime.html#timestamps-and-timezones seems like it might be the fix?

**Comment by nickbabcock** [comment]
Looks like this bug slipped through testing. There's a fix coming shortly. Thank you for reporting the issue 👍
