### ISSUE TITLE
Fatal error when virtual RamDisk is running 

### ISSUE THREAD

**Issue by EugeneSoftwareDeveloper** [nickbabcock/OhmGraphite#412]
When run [ramDisk](http://radeonramdisk.com/software_downloads.php)

![image](https://github.com/nickbabcock/OhmGraphite/assets/61660571/0c896620-6645-452d-b870-3cf5e3d4be7f)

![image](https://github.com/nickbabcock/OhmGraphite/assets/61660571/50881cf8-a624-4086-86c1-dd033de4076e)

When ramdisk is stoped there is no error

Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.SpanHelpers.IndexOf(Byte ByRef, Byte, Int32)
   at System.String.Ctor(SByte*)
   at System.Runtime.InteropServices.Marshal.PtrToStringAnsi(IntPtr)
   at LibreHardwareMonitor.Hardware.Storage.WindowsStorage+StorageInfo.GetString(IntPtr, UInt32)
   at LibreHardwareMonitor.Hardware.Storage.WindowsStorage+StorageInfo..ctor(Int32, IntPtr)
   at LibreHardwareMonitor.Hardware.Storage.WindowsStorage.GetStorageInfo(System.String, UInt32)
   at LibreHardwareMonitor.Hardware.Storage.AbstractStorage.CreateInstance(System.String, UInt32, UInt64, Int32, LibreHardwareMonitor.Hardware.ISettings)
   at LibreHardwareMonitor.Hardware.Storage.StorageGroup.AddHardware(LibreHardwareMonitor.Hardware.ISettings, System.Collections.Generic.Dictionary`2<UInt32,System.Collections.Generic.List`1<System.ValueTuple`2<UInt32,UInt64>>>)
   at LibreHardwareMonitor.Hardware.Storage.StorageGroup..ctor(LibreHardwareMonitor.Hardware.ISettings)
   at LibreHardwareMonitor.Hardware.Computer.AddGroups()
   at LibreHardwareMonitor.Hardware.Computer.Open()
   at OhmGraphite.SensorCollector.Start()
   at OhmGraphite.PrometheusServer.<Start>b__4_0()
   at OhmGraphite.LoggerUtils.LogAction(NLog.Logger, System.String, System.Action)
   at OhmGraphite.PrometheusServer.Start()
   at OhmGraphite.Worker+<>c__DisplayClass3_0.<ExecuteAsync>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task+<>c.<.cctor>b__272_0(System.Object)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
   at System.Threading.Tasks.Task.ExecuteEntryUnsafe(System.Threading.Thread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()

**Comment by nickbabcock** [comment]
Is the ramdisk included in the gui or has it been excluded?

**Comment by EugeneSoftwareDeveloper** [comment]
The patition is not displayed. Only displayed hard disks and ssd.

RamDisk is not displayed (excluded). 

![image](https://github.com/nickbabcock/OhmGraphite/assets/61660571/e7223b82-809f-4b0e-9245-f120e3546ace)

**Comment by nickbabcock** [comment]
Do you get the same error when you run OhmGraphite interactively (in an administrator terminal)?

```pwsh
./OhmGraphite stop
./OhmGraphite run
```

**Comment by EugeneSoftwareDeveloper** [comment]
> Do you get the same error when you run OhmGraphite interactively (in an administrator terminal)?
> 
> ```powershell
> ./OhmGraphite stop
> ./OhmGraphite run
> ```

Also stops after starting.
Run as admin

![image](https://github.com/nickbabcock/OhmGraphite/assets/61660571/9f3297a1-8304-49e2-ada1-7630babd9e06)

**Comment by nickbabcock** [comment]
The screenshot is a little confusing. To run interactively, execute `OhmGraphite.exe run` (the screenshot shows `OhmGraphite.exe start`)

**Comment by EugeneSoftwareDeveloper** [comment]
> The screenshot is a little confusing. To run interactively, execute `OhmGraphite.exe run` (the screenshot shows `OhmGraphite.exe start`)

c:\Program Files\OhmGraphite>OhmGraphite.exe run
2024-02-01 17:29:11.0961|INFO|OhmGraphite.Worker|Prometheus port: 2003
2024-02-01 17:29:11.2325|INFO|OhmGraphite.SensorCollector|Sensor added: /lpc/nct6798d/control/0 "Fan #1"
2024-02-01 17:29:11.2325|INFO|OhmGraphite.SensorCollector|Sensor added: /lpc/nct6798d/control/1 "Fan #2"
2024-02-01 17:29:11.2325|INFO|OhmGraphite.SensorCollector|Sensor added: /lpc/nct6798d/control/2 "Fan #3"
2024-02-01 17:29:11.2325|INFO|OhmGraphite.SensorCollector|Sensor added: /lpc/nct6798d/control/3 "Fan #4"
2024-02-01 17:29:11.2325|INFO|OhmGraphite.SensorCollector|Sensor added: /lpc/nct6798d/control/4 "Fan #5"
2024-02-01 17:29:11.2325|INFO|OhmGraphite.SensorCollector|Sensor added: /lpc/nct6798d/control/5 "Fan #6"
2024-02-01 17:29:11.2325|INFO|OhmGraphite.SensorCollector|Sensor added: /lpc/nct6798d/control/6 "Fan #7"
2024-02-01 17:29:11.2325|INFO|OhmGraphite.SensorCollector|Sensor added: /lpc/ec/temperature/0 "Chipset"
2024-02-01 17:29:11.2325|INFO|OhmGraphite.SensorCollector|Sensor added: /lpc/ec/temperature/1 "CPU"
2024-02-01 17:29:11.2325|INFO|OhmGraphite.SensorCollector|Sensor added: /lpc/ec/temperature/2 "Motherboard"
2024-02-01 17:29:11.2325|INFO|OhmGraphite.SensorCollector|Sensor added: /lpc/ec/temperature/3 "T Sensor"
2024-02-01 17:29:11.2325|INFO|OhmGraphite.SensorCollector|Sensor added: /lpc/ec/temperature/4 "VRM"
2024-02-01 17:29:11.2325|INFO|OhmGraphite.SensorCollector|Sensor added: /lpc/ec/voltage/0 "CPU Core"
2024-02-01 17:29:11.2325|INFO|OhmGraphite.SensorCollector|Sensor added: /lpc/ec/fan/0 "Chipset Fan"
2024-02-01 17:29:11.2325|INFO|OhmGraphite.SensorCollector|Sensor added: /lpc/ec/current/0 "CPU"
2024-02-01 17:29:11.3579|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/load/2 "CPU Core #1"
2024-02-01 17:29:11.3579|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/load/3 "CPU Core #2"
2024-02-01 17:29:11.3579|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/load/4 "CPU Core #3"
2024-02-01 17:29:11.3579|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/load/5 "CPU Core #4"
2024-02-01 17:29:11.3579|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/load/6 "CPU Core #5"
2024-02-01 17:29:11.3579|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/load/7 "CPU Core #6"
2024-02-01 17:29:11.3579|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/load/8 "CPU Core #7"
2024-02-01 17:29:11.3579|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/load/9 "CPU Core #8"
2024-02-01 17:29:11.3579|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/load/10 "CPU Core #9"
2024-02-01 17:29:11.3579|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/load/11 "CPU Core #10"
2024-02-01 17:29:11.3579|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/load/12 "CPU Core #11"
2024-02-01 17:29:11.3579|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/load/13 "CPU Core #12"
2024-02-01 17:29:11.3579|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/load/14 "CPU Core #13"
2024-02-01 17:29:11.3579|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/load/15 "CPU Core #14"
2024-02-01 17:29:11.3579|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/load/16 "CPU Core #15"
2024-02-01 17:29:11.3579|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/load/17 "CPU Core #16"
2024-02-01 17:29:11.3579|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/load/18 "CPU Core #17"
2024-02-01 17:29:11.3579|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/load/19 "CPU Core #18"
2024-02-01 17:29:11.3579|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/load/20 "CPU Core #19"
2024-02-01 17:29:11.3579|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/load/21 "CPU Core #20"
2024-02-01 17:29:11.3579|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/load/22 "CPU Core #21"
2024-02-01 17:29:11.3579|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/load/23 "CPU Core #22"
2024-02-01 17:29:11.3579|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/load/24 "CPU Core #23"
2024-02-01 17:29:11.3579|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/load/25 "CPU Core #24"
2024-02-01 17:29:11.3579|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/load/0 "CPU Total"
2024-02-01 17:29:11.3579|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/load/1 "CPU Core Max"
2024-02-01 17:29:11.3579|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/power/0 "Package"
2024-02-01 17:29:11.3579|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/clock/20 "Core #1"
2024-02-01 17:29:11.3579|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/factor/0 "Core #1"
2024-02-01 17:29:11.3579|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/power/1 "Core #1 (SMU)"
2024-02-01 17:29:11.3579|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/voltage/2 "Core #1 VID"
2024-02-01 17:29:11.3579|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/clock/21 "Core #2"
2024-02-01 17:29:11.3579|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/factor/1 "Core #2"
2024-02-01 17:29:11.3579|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/power/2 "Core #2 (SMU)"
2024-02-01 17:29:11.3579|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/voltage/3 "Core #2 VID"
2024-02-01 17:29:11.3579|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/clock/22 "Core #3"
2024-02-01 17:29:11.3579|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/factor/2 "Core #3"
2024-02-01 17:29:11.3579|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/power/3 "Core #3 (SMU)"
2024-02-01 17:29:11.3579|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/voltage/4 "Core #3 VID"
2024-02-01 17:29:11.3579|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/clock/23 "Core #4"
2024-02-01 17:29:11.3710|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/factor/3 "Core #4"
2024-02-01 17:29:11.3710|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/power/4 "Core #4 (SMU)"
2024-02-01 17:29:11.3710|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/voltage/5 "Core #4 VID"
2024-02-01 17:29:11.3710|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/clock/24 "Core #5"
2024-02-01 17:29:11.3710|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/factor/4 "Core #5"
2024-02-01 17:29:11.3710|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/power/5 "Core #5 (SMU)"
2024-02-01 17:29:11.3710|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/voltage/6 "Core #5 VID"
2024-02-01 17:29:11.3710|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/clock/25 "Core #6"
2024-02-01 17:29:11.3710|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/factor/5 "Core #6"
2024-02-01 17:29:11.3710|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/power/6 "Core #6 (SMU)"
2024-02-01 17:29:11.3710|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/voltage/7 "Core #6 VID"
2024-02-01 17:29:11.3710|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/clock/26 "Core #7"
2024-02-01 17:29:11.3710|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/factor/6 "Core #7"
2024-02-01 17:29:11.3710|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/power/7 "Core #7 (SMU)"
2024-02-01 17:29:11.3710|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/voltage/8 "Core #7 VID"
2024-02-01 17:29:11.3710|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/clock/27 "Core #8"
2024-02-01 17:29:11.3710|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/factor/7 "Core #8"
2024-02-01 17:29:11.3710|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/power/8 "Core #8 (SMU)"
2024-02-01 17:29:11.3710|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/voltage/9 "Core #8 VID"
2024-02-01 17:29:11.3710|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/clock/28 "Core #9"
2024-02-01 17:29:11.3710|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/factor/8 "Core #9"
2024-02-01 17:29:11.3710|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/power/9 "Core #9 (SMU)"
2024-02-01 17:29:11.3710|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/voltage/10 "Core #9 VID"
2024-02-01 17:29:11.3710|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/clock/29 "Core #10"
2024-02-01 17:29:11.3710|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/factor/9 "Core #10"
2024-02-01 17:29:11.3710|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/power/10 "Core #10 (SMU)"
2024-02-01 17:29:11.3710|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/voltage/11 "Core #10 VID"
2024-02-01 17:29:11.3710|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/clock/30 "Core #11"
2024-02-01 17:29:11.3710|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/factor/10 "Core #11"
2024-02-01 17:29:11.3710|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/power/11 "Core #11 (SMU)"
2024-02-01 17:29:11.3710|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/voltage/12 "Core #11 VID"
2024-02-01 17:29:11.3710|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/clock/31 "Core #12"
2024-02-01 17:29:11.3710|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/factor/11 "Core #12"
2024-02-01 17:29:11.3710|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/power/12 "Core #12 (SMU)"
2024-02-01 17:29:11.3710|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/voltage/13 "Core #12 VID"
2024-02-01 17:29:11.3710|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/temperature/2 "Core (Tctl/Tdie)"
2024-02-01 17:29:11.3710|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/temperature/4 "CCD1 (Tdie)"
2024-02-01 17:29:11.3710|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/temperature/5 "CCD2 (Tdie)"
2024-02-01 17:29:11.3710|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/temperature/6 "CCDs Max (Tdie)"
2024-02-01 17:29:11.3710|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/temperature/7 "CCDs Average (Tdie)"
2024-02-01 17:29:11.3710|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/voltage/0 "Core (SVI2 TFN)"
2024-02-01 17:29:11.3710|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/voltage/1 "SoC (SVI2 TFN)"
2024-02-01 17:29:11.3710|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/clock/0 "Bus Speed"
2024-02-01 17:29:11.3868|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/current/0 "TDC"
2024-02-01 17:29:11.3868|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/clock/1 "Fabric"
2024-02-01 17:29:11.3868|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/clock/2 "Uncore"
2024-02-01 17:29:11.3868|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/clock/3 "Memory"
2024-02-01 17:29:11.3868|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/temperature/3 "SoC"
2024-02-01 17:29:11.3868|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/clock/4 "Core #1 (Effective)"
2024-02-01 17:29:11.3868|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/clock/5 "Core #2 (Effective)"
2024-02-01 17:29:11.3868|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/clock/7 "Core #4 (Effective)"
2024-02-01 17:29:11.3868|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/clock/8 "Core #5 (Effective)"
2024-02-01 17:29:11.3868|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/clock/10 "Core #7 (Effective)"
2024-02-01 17:29:11.3868|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/clock/11 "Core #8 (Effective)"
2024-02-01 17:29:11.3868|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/clock/12 "Core #9 (Effective)"
2024-02-01 17:29:11.3868|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/clock/13 "Core #10 (Effective)"
2024-02-01 17:29:11.3868|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/clock/16 "Core #13 (Effective)"
2024-02-01 17:29:11.3868|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/clock/17 "Core #14 (Effective)"
2024-02-01 17:29:11.3868|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/clock/18 "Core #15 (Effective)"
2024-02-01 17:29:11.3868|INFO|OhmGraphite.SensorCollector|Sensor added: /amdcpu/0/clock/19 "Core #16 (Effective)"
2024-02-01 17:29:11.3868|INFO|OhmGraphite.SensorCollector|Sensor added: /ram/data/0 "Memory Used"
2024-02-01 17:29:11.3868|INFO|OhmGraphite.SensorCollector|Sensor added: /ram/data/1 "Memory Available"
2024-02-01 17:29:11.3868|INFO|OhmGraphite.SensorCollector|Sensor added: /ram/load/0 "Memory"
2024-02-01 17:29:11.3868|INFO|OhmGraphite.SensorCollector|Sensor added: /ram/data/2 "Virtual Memory Used"
2024-02-01 17:29:11.3868|INFO|OhmGraphite.SensorCollector|Sensor added: /ram/data/3 "Virtual Memory Available"
2024-02-01 17:29:11.3868|INFO|OhmGraphite.SensorCollector|Sensor added: /ram/load/1 "Virtual Memory"
2024-02-01 17:29:11.5795|INFO|OhmGraphite.SensorCollector|Sensor added: /gpu-nvidia/0/temperature/0 "GPU Core"
2024-02-01 17:29:11.5795|INFO|OhmGraphite.SensorCollector|Sensor added: /gpu-nvidia/0/clock/0 "GPU Core"
2024-02-01 17:29:11.5795|INFO|OhmGraphite.SensorCollector|Sensor added: /gpu-nvidia/0/clock/4 "GPU Memory"
2024-02-01 17:29:11.5795|INFO|OhmGraphite.SensorCollector|Sensor added: /gpu-nvidia/0/fan/1 "GPU Fan 1"
2024-02-01 17:29:11.5795|INFO|OhmGraphite.SensorCollector|Sensor added: /gpu-nvidia/0/fan/2 "GPU Fan 2"
2024-02-01 17:29:11.5795|INFO|OhmGraphite.SensorCollector|Sensor added: /gpu-nvidia/0/control/1 "GPU Fan 1"
2024-02-01 17:29:11.5795|INFO|OhmGraphite.SensorCollector|Sensor added: /gpu-nvidia/0/control/2 "GPU Fan 2"
2024-02-01 17:29:11.5795|INFO|OhmGraphite.SensorCollector|Sensor added: /gpu-nvidia/0/load/0 "GPU Core"
2024-02-01 17:29:11.5795|INFO|OhmGraphite.SensorCollector|Sensor added: /gpu-nvidia/0/load/1 "GPU Memory Controller"
2024-02-01 17:29:11.5795|INFO|OhmGraphite.SensorCollector|Sensor added: /gpu-nvidia/0/load/2 "GPU Video Engine"
2024-02-01 17:29:11.5795|INFO|OhmGraphite.SensorCollector|Sensor added: /gpu-nvidia/0/load/3 "GPU Bus"
2024-02-01 17:29:11.5795|INFO|OhmGraphite.SensorCollector|Sensor added: /gpu-nvidia/0/load/4 "GPU Power"
2024-02-01 17:29:11.5795|INFO|OhmGraphite.SensorCollector|Sensor added: /gpu-nvidia/0/load/5 "GPU Board Power"
2024-02-01 17:29:11.5795|INFO|OhmGraphite.SensorCollector|Sensor added: /gpu-nvidia/0/smalldata/4 "D3D Dedicated Memory Used"
2024-02-01 17:29:11.5795|INFO|OhmGraphite.SensorCollector|Sensor added: /gpu-nvidia/0/smalldata/5 "D3D Shared Memory Used"
2024-02-01 17:29:11.5795|INFO|OhmGraphite.SensorCollector|Sensor added: /gpu-nvidia/0/load/6 "D3D 3D"
2024-02-01 17:29:11.5795|INFO|OhmGraphite.SensorCollector|Sensor added: /gpu-nvidia/0/load/7 "D3D Compute_0"
2024-02-01 17:29:11.5795|INFO|OhmGraphite.SensorCollector|Sensor added: /gpu-nvidia/0/load/17 "D3D Overlay"
2024-02-01 17:29:11.5795|INFO|OhmGraphite.SensorCollector|Sensor added: /gpu-nvidia/0/load/19 "D3D Video Decode"
2024-02-01 17:29:11.5795|INFO|OhmGraphite.SensorCollector|Sensor added: /gpu-nvidia/0/load/9 "D3D Copy"
2024-02-01 17:29:11.5795|INFO|OhmGraphite.SensorCollector|Sensor added: /gpu-nvidia/0/load/10 "D3D Copy"
2024-02-01 17:29:11.5795|INFO|OhmGraphite.SensorCollector|Sensor added: /gpu-nvidia/0/load/18 "D3D Security"
2024-02-01 17:29:11.5795|INFO|OhmGraphite.SensorCollector|Sensor added: /gpu-nvidia/0/load/20 "D3D Video Encode"
2024-02-01 17:29:11.5795|INFO|OhmGraphite.SensorCollector|Sensor added: /gpu-nvidia/0/load/21 "D3D Video Processing"
2024-02-01 17:29:11.5795|INFO|OhmGraphite.SensorCollector|Sensor added: /gpu-nvidia/0/load/16 "D3D Graphics_1"
2024-02-01 17:29:11.5795|INFO|OhmGraphite.SensorCollector|Sensor added: /gpu-nvidia/0/load/15 "D3D Cuda"
2024-02-01 17:29:11.5795|INFO|OhmGraphite.SensorCollector|Sensor added: /gpu-nvidia/0/load/8 "D3D Compute_1"
2024-02-01 17:29:11.5795|INFO|OhmGraphite.SensorCollector|Sensor added: /gpu-nvidia/0/load/22 "D3D VR"
2024-02-01 17:29:11.5892|INFO|OhmGraphite.SensorCollector|Sensor added: /gpu-nvidia/0/load/11 "D3D Copy"
2024-02-01 17:29:11.5892|INFO|OhmGraphite.SensorCollector|Sensor added: /gpu-nvidia/0/load/12 "D3D Copy"
2024-02-01 17:29:11.5892|INFO|OhmGraphite.SensorCollector|Sensor added: /gpu-nvidia/0/load/13 "D3D Copy"
2024-02-01 17:29:11.5892|INFO|OhmGraphite.SensorCollector|Sensor added: /gpu-nvidia/0/load/14 "D3D Copy"
2024-02-01 17:29:11.5892|INFO|OhmGraphite.SensorCollector|Sensor added: /gpu-nvidia/0/temperature/2 "GPU Hot Spot"
2024-02-01 17:29:11.5892|INFO|OhmGraphite.SensorCollector|Sensor added: /gpu-nvidia/0/temperature/3 "GPU Memory Junction"
2024-02-01 17:29:11.5892|INFO|OhmGraphite.SensorCollector|Sensor added: /gpu-nvidia/0/smalldata/2 "GPU Memory Total"
2024-02-01 17:29:11.5892|INFO|OhmGraphite.SensorCollector|Sensor added: /gpu-nvidia/0/smalldata/0 "GPU Memory Free"
2024-02-01 17:29:11.5892|INFO|OhmGraphite.SensorCollector|Sensor added: /gpu-nvidia/0/smalldata/1 "GPU Memory Used"
2024-02-01 17:29:11.5892|INFO|OhmGraphite.SensorCollector|Sensor previously added: /gpu-nvidia/0/load/3 "GPU Memory"
2024-02-01 17:29:11.5892|INFO|OhmGraphite.SensorCollector|Sensor added: /gpu-nvidia/0/power/0 "GPU Package"
2024-02-01 17:29:11.5892|INFO|OhmGraphite.SensorCollector|Sensor added: /gpu-nvidia/0/throughput/0 "GPU PCIe Rx"
2024-02-01 17:29:11.5892|INFO|OhmGraphite.SensorCollector|Sensor added: /gpu-nvidia/0/throughput/1 "GPU PCIe Tx"
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.SpanHelpers.IndexOf(Byte ByRef, Byte, Int32)
   at System.String.Ctor(SByte*)
   at System.Runtime.InteropServices.Marshal.PtrToStringAnsi(IntPtr)
   at LibreHardwareMonitor.Hardware.Storage.WindowsStorage+StorageInfo.GetString(IntPtr, UInt32)
   at LibreHardwareMonitor.Hardware.Storage.WindowsStorage+StorageInfo..ctor(Int32, IntPtr)
   at LibreHardwareMonitor.Hardware.Storage.WindowsStorage.GetStorageInfo(System.String, UInt32)
   at LibreHardwareMonitor.Hardware.Storage.AbstractStorage.CreateInstance(System.String, UInt32, UInt64, Int32, LibreHardwareMonitor.Hardware.ISettings)
   at LibreHardwareMonitor.Hardware.Storage.StorageGroup.AddHardware(LibreHardwareMonitor.Hardware.ISettings, System.Collections.Generic.Dictionary`2<UInt32,System.Collections.Generic.List`1<System.ValueTuple`2<UInt32,UInt64>>>)
   at LibreHardwareMonitor.Hardware.Storage.StorageGroup..ctor(LibreHardwareMonitor.Hardware.ISettings)
   at LibreHardwareMonitor.Hardware.Computer.AddGroups()
   at LibreHardwareMonitor.Hardware.Computer.Open()
   at OhmGraphite.SensorCollector.Start()
   at OhmGraphite.PrometheusServer.<Start>b__4_0()
   at OhmGraphite.LoggerUtils.LogAction(NLog.Logger, System.String, System.Action)
   at OhmGraphite.PrometheusServer.Start()
   at OhmGraphite.Worker+<>c__DisplayClass3_0.<ExecuteAsync>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task+<>c.<.cctor>b__272_0(System.Object)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
   at System.Threading.Tasks.Task.ExecuteEntryUnsafe(System.Threading.Thread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()

**Comment by nickbabcock** [comment]
Thank you for posting, and your patience.

Tracing the logic, both LibreHardwareMonitor and OhmGraphite execute the same code, and while I don't know for 100%, it seems like the kernel is exposing different values to both. LibreHardwareMonitor receives either an invalid result or a false return from `DeviceIoControl` which is why it excludes it. For some reason, OhmGraphite doesn't and thinks the drive is valid (and thus fails).

I'm not sure what the next step is. Very confusing.

**Comment by nickbabcock** [comment]
This should be fixed in v0.34, let me know if otherwise.
